#!/usr/bin/env bash
export APPROVALS_DIR=$PWD/test/approvals
PATH="$PWD:$PATH"
pushd test/sample-repo > /dev/null
source "../approvals.bash"


describe "--help"
  approve "git-changelog --help"

describe "changelog"
  approve "git-changelog"

describe "--tail N"
  approve "git-changelog --tail 2"

describe "--color OPTION"
  approve "git-changelog --color off"

describe "--out PATH"
  rm -f out.md
  git-changelog --out out.md
  approve "cat out.md"
  rm -f out.md


blue PASS ALL
popd > /dev/null
