#!/usr/bin/env bash

print_in_color() {
  local color="$1"
  shift
  if [[ -z ${NO_COLOR+x} ]]; then
    printf "$color%b\e[0m\n" "$*"
  else
    printf "%b\n" "$*"
  fi
}

red() { print_in_color "\e[31m" "$*"; }
green() { print_in_color "\e[32m" "$*"; }
green_bold() { print_in_color "\e[1;32m" "$*"; }
blue() { print_in_color "\e[34m" "$*"; }

section() {
  echo -e "\n=== $(green_bold "$@")"
}

copy() {
  echo -e "$(blue "    $1") => $2"
  # shellcheck disable=SC2086
  cp "$origin"/$1 "$2"
}

sudo_copy() {
  echo -e "$(blue "    $1") => $2"
  # shellcheck disable=SC2086
  $sudo cp "$origin"/$1 "$2"
}

command_exist() {
  [[ -x "$(command -v "$1")" ]]
}

need() {
  command_exist "$1" || fail "Cannot run $1"
  echo -e "$(blue "    $1") found"
}

onerror() {
  local exit_status=$?
  echo -e "\n=== $(red "Aborted with exit status $exit_status")"
  exit $exit_status
}

fail() {
  echo -e "$(red ERR) $*"
  return 1
}

initialize() {
  set -e
  trap 'onerror' ERR

  # Figure out if we need sudo or not
  sudo=''
  if [[ $EUID -ne 0 ]]; then
    sudo='sudo'
  fi

  repo="$1"
  repo_url="https://github.com/${repo}.git"
  origin=$(mktemp -d)
}

section "Initializing"
initialize "DannyBen/git-changelog"

section "Checking for pre-requisites"
need git

section "Cloning $repo"
git clone --depth 1 "$repo_url" "$origin"

section "Copying files"
sudo_copy "git-changelog" "/usr/local/bin/"
$sudo chmod a+x /usr/local/bin/git-changelog
sudo_copy 'doc/git-changelog.1' "/usr/local/share/man/man1/"

section "Done"
git-changelog --version
