name: Test

on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install test dependencies
      run: sudo apt install faketime

    - name: Install opcode
      run: bash <(curl -Ls get.dannyb.co/opcode/setup)

    - name: Configure git
      run: |
        git config --global user.email "tester@approvals.com"
        git config --global user.name "Approvals Tester"
        git config --global init.defaultBranch master

    - name: Run shellcheck tests
      run: shellcheck git-changelog

    - name: Initialize test repo
      run: op sample-init

    - name: Run approval tests
      run: op test

  ubuntu_setup:
    name: Setup on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run setup
      run: ./setup

  macos_setup:
    name: Setup on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Upgrade the outdated bash
      run: brew install bash
    - name: Run setup
      run: ./setup

  static_analysis:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Rush needed for easy installation of latest shfmt
    - name: Install rush
      run: curl -Ls http://get.dannyb.co/rush/setup | bash

    - name: Connect rush repo
      run: rush clone dannyben --shallow --default

    - name: Install shfmt and opcode
      run: rush get shfmt && rush get opcode

    - name: Run shellcheck tests
      run: op shellcheck

    - name: Run shfmt tests
      run: op shfmt
